-- AlterTable
ALTER TABLE `Game` ADD COLUMN `moves` JSON NULL,
    ADD COLUMN `winnerId` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `Game` ADD CONSTRAINT `Game_winnerId_fkey` FOREIGN KEY (`winnerId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
